### PR TITLE
Ecs support

### PR DESCRIPTION
**Pull request by jkp85**
Signed-off-by: Jan Kowalski <jankowalskipraca85@gmail.com>

### CODE REVIEW

**Comment by roachmd** [comment]
@jkp85, So, for the userservers we will need either a task service to start traefik or a batch to start Traefik. I have an example of how we are currently deploying Traefik to the user servers.

**Comment by jkp85** [comment]
@roachmd We don't need traefik on user servers. Traefik instance from docker-compose will handle that.

**Comment by roachmd** [comment]
@jkp85 Lets make changes directly to https://github.com/3Blades/devops/blob/master/configs/dev-env/api/traefik.toml

**Comment by roachmd** [comment]
@jkp85 @johngriebel , I think we need to merge this also to get traefik working in dev with ECS.

**Pull request merged**
